### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by n0nag0n** [splitbrain/commie#7]
Needed a simple tool to create pastes and then make simple comments on them. It's surprising just how few options there are out. Found this repo from a link here https://github.com/isaacs/github/issues/243#issuecomment-754010745 and seriously saved me time to build out my own thing. 

Thanks so much!

**Comment by splitbrain** [comment]
You're welcome :-)

**Comment by n0nag0n** [comment]
FWIW, this is what I've been having fun with :) 

https://github.com/n0nag0n/commie2
